[package]
name = "Simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] } #delete feature before building release build!
bevy_easings = "0.11"
#bevy_panorbit_camera = { git = "https://github.com/jan-tennert/bevy_panorbit_camera", rev = "7e3c3f8" }
bevy-inspector-egui = { version = "0.19", default-features = false }
#bevy_mod_picking = "0.15"
bevy_screen_diagnostics = "0.3"
bevy_egui = "0.21"
chrono = "0.4.23"