[package]
name = "Simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "release-0.11.3", features = ["dynamic_linking"] } 
bevy = { version = "0.11.3" }
bevy_easings = "0.11.1"
#bevy_panorbit_camera = { git = "https://github.com/jan-tennert/bevy_panorbit_camera", rev = "7e3c3f8" }
bevy-inspector-egui = { version = "0.19", default-features = true }
#bevy_mod_picking = "0.15"
bevy_egui = "0.21"
chrono = "0.4.23"

[patch.crates-io]
bevy = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_ecs = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_app = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_tasks = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_reflect = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_core = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_asset = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_math = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_render = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_hierarchy = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_log = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_utils = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_window = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_pbr = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }
bevy_transform = { git = "https://github.com/jan-tennert/bevy", branch = "skybox-fix" }