[package]
name = "Simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[build-dependencies]
embed-resource = "1.6.3"

[dependencies]
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "release-0.11.3", features = ["dynamic_linking"] } 
bevy = { version = "0.12" }
bevy_easings = "0.12.2"
#bevy_panorbit_camera = { git = "https://github.com/jan-tennert/bevy_panorbit_camera", rev = "7e3c3f8" }
bevy-inspector-egui = { version = "0.21", default-features = false }
#bevy_mod_picking = "0.15"
bevy_egui = "0.23"
chrono = "0.4.31"
serde_json = "1.0.107"
serde = { version = "1.0.189", features = ["derive"] }
winit = "0.28.7"
image = "0.24.7"
bevy_mod_billboard = { git = "https://github.com/robtfm/bevy_mod_billboard/", branch = "bevy12" }
