on:
  push:
    branches: [main]
permissions: 
   contents: read 
   pages: write 
   id-token: write 
  
 # Allow one concurrent deployment
concurrency: 
  group: "pages" 
  cancel-in-progress: true  

jobs:
  test:
    environment: 
       name: github-pages 
       url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            target: wasm32-unknown-unknown

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cache-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cache-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
            cache-${{ runner.os }}-cargo
            
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Run build
        run: cargo build --profile wasm-release --target wasm32-unknown-unknown
      - name: WASM
        run: wasm-bindgen --out-dir out/ --target web ./target/wasm32-unknown-unknown/release/Simulation.wasm
      - name: Copy Assets
        run: |
          cp -r assets out/.

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1